# Generated by Django 2.2 on 2019-06-05 14:24

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190603_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_pro',
            fields=[
            ],
            options={
                'verbose_name': '分公司管理（代理）',
                'verbose_name_plural': '分公司管理（代理）',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.company',),
        ),
        migrations.CreateModel(
            name='UserProfile_pro',
            fields=[
            ],
            options={
                'verbose_name': '用户(代理)',
                'verbose_name_plural': '用户(代理)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
