# Generated by Django 2.2 on 2019-06-05 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20190603_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='请根据合同期限填写截止日期，所有超期未办结的资质类单子将在首页进行提醒', null=True, verbose_name='预计合同截止日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 5), verbose_name='签单日期'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pay_type',
            field=models.CharField(choices=[('收款', '收款'), ('退款', '退款')], default='收款', max_length=10, verbose_name='收款/退款'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='received_acount',
            field=models.CharField(choices=[('贵州银行', '贵州银行'), ('贵州银行8243', '贵州银行8243'), ('贵州银行510', '贵州银行510'), ('工商银行624', '工商银行624'), ('建设银行', '建设银行')], default='贵州银行', max_length=50, verbose_name='收款帐号'),
        ),
    ]
