# Generated by Django 2.2 on 2019-06-06 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20190605_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 6), verbose_name='签单日期'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='contract',
            field=models.OneToOneField(default=610, on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='合同'),
            preserve_default=False,
        ),
    ]
