# Generated by Django 2.2 on 2019-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20190610_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('资质合同', '资质合同'), ('工商', '工商'), ('工商注销', '工商注销'), ('解除合同', '解除合同'), ('补充合同', '补充合同'), ('食品经营', '食品经营'), ('条形码', '条形码'), ('财务记账', '财务记账'), ('人力资源', '人力资源'), ('认证服务', '认证服务'), ('网站开发', '网站开发'), ('人力资源', '人力资源'), ('商标', '商标'), ('委托协议', '委托协议'), ('培训协议', '培训协议'), ('LOGO设计', 'LOGO设计'), ('人才协议', '人才协议'), ('专利合同', '专利合同'), ('企业咨询', '企业咨询'), ('著作权', '著作权'), ('专利合同', '专利合同')], default='资质合同', max_length=200, verbose_name='合同分类'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pay_dep',
            field=models.CharField(blank=True, help_text='请填写对方打款具体银行及汇款帐号，电子支付填写微信/支付宝等应用名称', max_length=50, verbose_name='银行帐号/机构名称'),
        ),
    ]
