# Generated by Django 2.2 on 2019-06-13 14:08

import contract.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_auto_20190610_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, help_text='上传jpg或pnp的zip压缩文件（不支持rar），后台会自动合成PDF，以支持在线预览', null=True, upload_to=contract.models.contract_path, verbose_name='相关附件'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 13), verbose_name='签单日期'),
        ),
        migrations.AlterField(
            model_name='prgsheet',
            name='file',
            field=models.FileField(blank=True, help_text='上传jpg或pnp的zip压缩文件（不支持rar），后台会自动合成PDF，以支持在线预览', null=True, upload_to=contract.models.prgsheet_path, verbose_name='相关附件'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='received_acount',
            field=models.CharField(choices=[('贵州银行', '贵州银行'), ('贵州银行8243', '贵州银行8243'), ('贵州银行510', '贵州银行510'), ('工商银行624', '工商银行624'), ('建设银行', '建设银行'), ('首辰财务对公', '首辰财务对公'), ('电子支付', '电子支付'), ('现金', '现金')], default='贵州银行', max_length=50, verbose_name='收款帐号'),
        ),
    ]
