# Generated by Django 2.2 on 2019-06-18 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_auto_20190613_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ispropelling',
            field=models.BooleanField(default=False, verbose_name='是否通知消化部门'),
        ),
        migrations.AddField(
            model_name='contract',
            name='propellingtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='通知消化时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('资质合同', '资质合同'), ('工商', '工商'), ('工商注销', '工商注销'), ('解除合同', '解除合同'), ('补充合同', '补充合同'), ('食品经营', '食品经营'), ('条形码', '条形码'), ('财务记账', '财务记账'), ('人力资源', '人力资源'), ('认证服务', '认证服务'), ('网站开发', '网站开发'), ('人力资源', '人力资源'), ('商标', '商标'), ('委托协议', '委托协议'), ('培训协议', '培训协议'), ('LOGO设计', 'LOGO设计'), ('人才协议', '人才协议'), ('专利合同', '专利合同'), ('企业咨询', '企业咨询'), ('著作权', '著作权'), ('专利合同', '专利合同'), ('劳务派遣', '劳务派遣'), ('其他合同', '其他合同')], default='资质合同', max_length=200, verbose_name='合同分类'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 18), verbose_name='签单日期'),
        ),
    ]
