# Generated by Django 2.2 on 2019-06-19 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20190618_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prgsheet',
            name='xcglry',
        ),
        migrations.AddField(
            model_name='prgsheet',
            name='sanleirenyuan',
            field=models.TextField(blank=True, help_text='注明：级别', verbose_name='三类人员'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 19), verbose_name='签单日期'),
        ),
    ]
