# Generated by Django 2.2 on 2019-06-19 15:45

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20190619_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_contact',
        ),
        migrations.AddField(
            model_name='contract',
            name='file_to_pdf',
            field=models.BooleanField(default=True, help_text='勾选该选项，将默认将上传的zip压缩包转化为pdf，请确认压缩包格式为zip，并且压缩包中的图片格式为pnp或jpg', verbose_name='是否转化为PDF附件'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_path, verbose_name='合同附件'),
        ),
    ]
