# Generated by Django 2.2 on 2019-06-19 17:48

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_auto_20190619_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bcfile',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_path, verbose_name='补充合同附件'),
        ),
        migrations.AddField(
            model_name='contract',
            name='bcfile_to_pdf',
            field=models.BooleanField(default=True, verbose_name='转化为PDF'),
        ),
        migrations.AddField(
            model_name='contract',
            name='jcfile',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_path, verbose_name='解除/终止合同附件'),
        ),
        migrations.AddField(
            model_name='contract',
            name='jcfile_to_pdf',
            field=models.BooleanField(default=True, verbose_name='转化为PDF'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='正常状态', max_length=10, verbose_name='合同状态'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, help_text='勾选转化为PDF，会将默认将上传的zip压缩包转化为pdf，请确认压缩包格式为zip，并且压缩包中的图片格式为pnp或jpg', null=True, upload_to=contract.models.contract_path, verbose_name='合同附件'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_to_pdf',
            field=models.BooleanField(default=True, verbose_name='转化为PDF'),
        ),
    ]
