# Generated by Django 2.2 on 2019-06-25 14:56

import contract.models
import datetime
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_auto_20190619_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='bcfile',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(contract.models.set_file_path, *(), **{'modelname': 'contract', 'typename': '补充合同附件'}), verbose_name='补充合同附件'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, help_text='勾选转化为PDF，会将默认将上传的zip压缩包转化为pdf，请确认压缩包格式为zip，并且压缩包中的图片格式为pnp或jpg', null=True, upload_to=functools.partial(contract.models.set_file_path, *(), **{'modelname': 'contract', 'typename': '合同附件'}), verbose_name='合同附件'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ispropelling',
            field=models.BooleanField(default=False, verbose_name='通知消化部门'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='jcfile',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(contract.models.set_file_path, *(), **{'modelname': 'contract', 'typename': '解除合同附件'}), verbose_name='解除/终止合同附件'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 25), verbose_name='签单日期'),
        ),
        migrations.AlterField(
            model_name='prgsheet',
            name='file',
            field=models.FileField(blank=True, help_text='上传jpg或pnp的zip压缩文件（不支持rar），后台会自动合成PDF，以支持在线预览', null=True, upload_to=functools.partial(contract.models.set_file_path, *(), **{'modelname': 'prgsheet', 'typename': '进度表附件'}), verbose_name='相关附件'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='received_acount',
            field=models.CharField(choices=[('贵州银行', '贵州银行'), ('贵州银行8243', '贵州银行8243'), ('贵州银行510', '贵州银行510'), ('工商银行624', '工商银行624'), ('建设银行', '建设银行'), ('农业银行2174', '农业银行2174'), ('信用合作社', '信用合作社'), ('首途知产对公', '首途知产对公'), ('首辰财务对公', '首辰财务对公'), ('电子支付', '电子支付'), ('现金', '现金')], default='贵州银行', max_length=50, verbose_name='收款帐号'),
        ),
    ]
