# Generated by Django 2.2 on 2019-06-26 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lieguan', '0004_auto_20190626_1659'),
        ('contract', '0012_auto_20190625_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_bar',
            name='personel',
            field=models.ManyToManyField(blank=True, null=True, to='lieguan.Personnel', verbose_name='人才库'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 26), verbose_name='签单日期'),
        ),
    ]
