# Generated by Django 2.2 on 2019-06-27 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_auto_20190626_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signdate',
            field=models.DateField(default=datetime.date.today, verbose_name='签单日期'),
        ),
        migrations.AlterField(
            model_name='equipment_bar',
            name='personel',
            field=models.ManyToManyField(to='lieguan.Personnel', verbose_name='人才库'),
        ),
    ]
