# Generated by Django 2.2 on 2019-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_auto_20190627_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('正常状态', '正常状态'), ('补充后已解除', '补充后已解除'), ('经过补充', '经过补充'), ('已解除', '已解除')], default='正常状态', max_length=10, verbose_name='合同状态'),
        ),
        migrations.AlterField(
            model_name='equipment_bar',
            name='personel',
            field=models.ManyToManyField(blank=True, null=True, to='lieguan.Personnel', verbose_name='人才库'),
        ),
    ]
