# Generated by Django 2.2 on 2019-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_auto_20190627_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_bar',
            name='personel',
            field=models.ManyToManyField(blank=True, to='lieguan.Personnel', verbose_name='人才库'),
        ),
    ]
