# Generated by Django 2.2 on 2019-07-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_auto_20190627_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment_bar',
            options={'ordering': ['-id'], 'verbose_name': '配备条', 'verbose_name_plural': '配备条'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='Accepted',
            field=models.FloatField(default=0, verbose_name='收款单.已收'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('资质合同', '资质合同'), ('工商', '工商'), ('工商注销', '工商注销'), ('食品经营', '食品经营'), ('条形码', '条形码'), ('财务记账', '财务记账'), ('人力资源', '人力资源'), ('认证服务', '认证服务'), ('网站开发', '网站开发'), ('人力资源', '人力资源'), ('商标', '商标'), ('委托协议', '委托协议'), ('培训协议', '培训协议'), ('LOGO设计', 'LOGO设计'), ('人才协议', '人才协议'), ('专利合同', '专利合同'), ('企业咨询', '企业咨询'), ('著作权', '著作权'), ('专利合同', '专利合同'), ('劳务派遣', '劳务派遣'), ('其他合同', '其他合同')], default='资质合同', max_length=200, verbose_name='合同分类'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='receivable',
            field=models.FloatField(default=0, verbose_name='收款单.未收'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_price',
            field=models.FloatField(verbose_name='合同金额（元）'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='money',
            field=models.FloatField(verbose_name=' 费用金额(元)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_money',
            field=models.FloatField(default=0, verbose_name='总费用'),
        ),
        migrations.AlterField(
            model_name='equipment_bar',
            name='money',
            field=models.FloatField(default=0, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='prgsheet',
            name='totalcost',
            field=models.FloatField(default=0, verbose_name='成本汇总'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='money',
            field=models.FloatField(verbose_name='收款金额(元)'),
        ),
    ]
