# Generated by Django 2.2 on 2019-07-05 12:59

import common.middlewares
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0018_auto_20190705_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='founder',
            field=models.ForeignKey(blank=True, default=common.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='founder',
            field=models.ForeignKey(default=common.middlewares.get_current_user, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='founder',
            field=models.ForeignKey(default=common.middlewares.get_current_user, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
