# Generated by Django 2.2 on 2019-07-15 09:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_auto_20190708_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='finishtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最初配齐时间'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='finishtime_recorde',
            field=jsonfield.fields.JSONField(default=dict, max_length=1000, verbose_name='配齐时间记录'),
        ),
        migrations.AlterField(
            model_name='equipment_bar',
            name='personel',
            field=models.ManyToManyField(blank=True, to='lieguan.Personnel', verbose_name='系统人才库'),
        ),
        migrations.AlterField(
            model_name='equipment_bar',
            name='specific',
            field=models.CharField(blank=True, max_length=300, verbose_name='其他非系统人员'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='received_acount',
            field=models.CharField(choices=[('贵州银行', '贵州银行'), ('贵州银行8243', '贵州银行8243'), ('贵州银行510', '贵州银行510'), ('工商银行624', '工商银行624'), ('建设银行', '建设银行'), ('农业银行2174', '农业银行2174'), ('信用合作社', '信用合作社'), ('富明村镇银行', '富明村镇银行'), ('首途知产对公', '首途知产对公'), ('首辰财务对公', '首辰财务对公'), ('电子支付', '电子支付'), ('现金', '现金')], default='贵州银行', max_length=50, verbose_name='收款帐号'),
        ),
    ]
