# Generated by Django 2.2 on 2019-07-11 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_add_timestamp_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='href',
            field=models.CharField(max_length=200, null=True, verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='notification',
            name='msg',
            field=models.CharField(max_length=200, null=True, verbose_name='附语'),
        ),
        migrations.AddField(
            model_name='notification',
            name='nfrom',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='readedstamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('待发送', '待发送'), ('已发送', '已发送'), ('已读', '已读')], default='已发送', max_length=20, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='类型'),
        ),
    ]
