# Generated by Django 2.2 on 2019-06-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zizhireport',
            fields=[
            ],
            options={
                'verbose_name': '资质类业务专用报表',
                'verbose_name_plural': '资质类业务专用报表',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contract.contract',),
        ),
    ]
