# Generated by Django 2.2 on 2019-06-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zizhireport',
            options={'permissions': (('export_zizhireport', 'Can 导出资质类专用报表'),), 'verbose_name': '资质类业务专用报表', 'verbose_name_plural': '资质类业务专用报表'},
        ),
    ]
