# Generated by Django 2.2 on 2019-06-25 14:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0012_auto_20190625_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('num', models.CharField(help_text='注意，该身份证号不能重复', max_length=50, unique=True, verbose_name='身份证号')),
                ('contact_man', models.CharField(blank=True, max_length=200, verbose_name='联系人')),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='电话号码')),
                ('major_type', models.CharField(choices=[('建造师', '建造师'), ('技术负责人', '技术负责人'), ('工程师', '工程师'), ('现场管理人员', '现场管理人员'), ('技工', '技工'), ('特种工', '特种工'), ('三类人员', '三类人员'), ('其他注册类人员', '其他注册类人员'), ('其他', '其他')], max_length=200, verbose_name='所属大类')),
                ('level', models.CharField(blank=True, choices=[('初级', '初级'), ('中级', '中级'), ('高级', '高级'), ('一级', '一级'), ('二级', '二级'), ('三级', '三级'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200, verbose_name='级别/证书级别')),
                ('money', models.IntegerField(verbose_name='金额（元）')),
                ('singman', models.CharField(blank=True, max_length=200, verbose_name='签单人')),
                ('signdate', models.DateField(default=datetime.date(2019, 6, 25), verbose_name='合同签订日期')),
                ('enddate', models.DateField(default=datetime.date(2020, 6, 24), verbose_name='合同到期日期')),
                ('islive', models.BooleanField(default=True, verbose_name='是否可用')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('subject_or_worktype', models.ManyToManyField(help_text='如果没有您想要的专业/工种请点击右边的+添加', to='contract.Subject', verbose_name='工种/专业')),
            ],
            options={
                'verbose_name': '猎聘人才',
                'verbose_name_plural': '猎聘人才',
            },
        ),
    ]
