# Generated by Django 2.2 on 2019-06-25 16:45

from django.db import migrations, models
import functools
import lieguan.models


class Migration(migrations.Migration):

    dependencies = [
        ('lieguan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='file',
            field=models.FileField(blank=True, help_text='勾选转化为PDF，会将默认将上传的zip压缩包转化为pdf，请确认压缩包格式为zip，并且压缩包中的图片格式为pnp或jpg', null=True, upload_to=functools.partial(lieguan.models.set_file_path, *(), **{'modelname': 'contract', 'typename': '合同附件'}), verbose_name='合同附件'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='file_to_pdf',
            field=models.BooleanField(default=True, verbose_name='转化为PDF'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='num',
            field=models.CharField(blank=True, help_text='注意，该身份证号不能重复', max_length=50, unique=True, verbose_name='身份证号'),
        ),
    ]
