# Generated by Django 2.2 on 2019-06-25 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lieguan', '0002_auto_20190625_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
