# Generated by Django 2.2 on 2019-06-26 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lieguan', '0003_auto_20190625_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='enddate',
            field=models.DateField(default=datetime.date(2020, 6, 25), verbose_name='合同到期日期'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='signdate',
            field=models.DateField(default=datetime.date(2019, 6, 26), verbose_name='合同签订日期'),
        ),
    ]
