# Generated by Django 2.2 on 2019-06-27 18:03

import common.middlewares
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_auto_20190627_1803'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lieguan', '0006_auto_20190627_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='founder',
            field=models.ForeignKey(blank=True, default=common.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.CreateModel(
            name='Personnel_rc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract')),
                ('equipment_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Equipment_bar')),
                ('founder', models.ForeignKey(blank=True, default=common.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieguan.Personnel')),
            ],
            options={
                'verbose_name': '人才使用记录',
                'verbose_name_plural': '人才使用记录',
            },
        ),
    ]
