# Generated by Django 2.2 on 2019-07-03 16:25

from django.db import migrations, models
import functools
import lieguan.models


class Migration(migrations.Migration):

    dependencies = [
        ('lieguan', '0008_auto_20190701_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='canreuse',
            field=models.BooleanField(default=True, help_text='筛选选取时，默认选取可重用中已办结的，和不可重用中未被使用的（建造师默认可重用）', verbose_name='可否重复利用'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='file',
            field=models.FileField(blank=True, help_text='勾选转化为PDF，会将默认将上传的zip压缩包转化为pdf，请确认压缩包格式为zip，并且压缩包中的图片格式为pnp或jpg', null=True, upload_to=functools.partial(lieguan.models.set_file_path, *(), **{'modelname': 'personnel', 'typename': '合同附件'}), verbose_name='合同附件'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='money',
            field=models.FloatField(verbose_name='金额（元）'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='zsfile',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(lieguan.models.set_file_path, *(), **{'modelname': 'personnel', 'typename': '证书等其他附件'}), verbose_name='证书等其他附件'),
        ),
    ]
