# Generated by Django 2.2 on 2019-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='公司名称')),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='客户名称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='客户地址')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='所属城市')),
                ('contact_man', models.CharField(blank=True, max_length=200, verbose_name='联系人')),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='电话号码')),
                ('comment', models.TextField(blank=True, verbose_name='客户备注')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'permissions': (('viewall_custom', 'Can 查看所有客户'), ('viewcompany_custom', 'Can 查看分公司所有客户'), ('vewowner_custom', 'Can 查看个人客户'), ('export_custom', 'Can 导出客户')),
            },
        ),
    ]
