# Generated by Django 2.2 on 2019-06-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_custom_founder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
