# Generated by Django 2.2 on 2019-06-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_custom_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('text', models.TextField(verbose_name='内容')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
